### ISSUE TITLE
[Fix] CustomExceptions

### ISSUE THREAD

**Issue by jong-seoung** [BackDjango/initialize_django_jongseoung#11]
### 구현 기능 설명
기존 customexceptions의 가독성 및 확장성, 재사용성 향상을 위한 customexceptions 기능 수정

### 예상 소요 시간
최소 1일, 최대 3일

**Comment by DBrider3** [comment]
기간 산정까지,, 직장인이신데요?

**Comment by jong-seoung** [comment]
찾아보니 다들 기간 산정까지 하는것 같더라고요.
기간 산정을 정확히 어떤 원칙을 기준을 작성해야하는자 잘몰라서 유도리있게 선정했습니다.
